version: '3.7'

services:
    db:
        image: postgres:12        
        environment: 
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data/
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        command: bash -c "python /usr/src/dm_rest/manage.py migrate --noinput &&
                    python /usr/src/dm_rest/manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/dm_rest
        depends_on:
            - db
        env_file:
            - ./.env.dev
volumes:
    pg_data: