version: '3.7'

services:
    web:
        build: .
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - db
    db:
        image: postgres:12.0-alpine
        volumes: 
            - dm_pg_data:/var/lib/postgresql/dm_data/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: postgres
volumes: 
    dm_pg_data: